
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true


info:
  app:
    name: spring-boot-actuator
    version: 1.0.0
    test: test